### ISSUE TITLE
List of things TODO

### ISSUE THREAD

**Issue by alehuo** [alehuo/clubhouse-backend#25]
# TODO list

Checkmark indicates a completed task/feature.

## Controllers

- [x] UserController
- [x] AuthController
- [x] WatchController
- [x] CalendarEventController
- [x] LocationController
- [x] NewsPostController
- [x] MessageController
- [x] PermissionController
- [x] StatisticsController
- [x] StudentUnionController
- [x] KeyController (Manages keys)
- [x] KeyTypeController (Manages key types)
- [ ] DocumentController (Manages various documents, for example cleaning schedules)

### Test for controllers

- [x] UserController (/api/v1/users)
- [x] AuthController (/api/v1/authenticate)
- [x] WatchController (/api/v1/watch)
- [x] CalendarEventController (/api/v1/calendar)
- [ ] LocationController (/api/v1/location)
- [ ] NewsPostController (/api/v1/newspost)
- [ ] MessageController (/api/v1/message)
- [ ] PermissionController (/api/v1/permission)
- [ ] StatisticsController (/api/v1/statistics)
- [x] StudentUnionController (/api/v1/studentunion)
- [ ] KeyController (/api/v1/key)
- [x] KeyTypeController (/api/v1/keyType)
- [ ] DocumentController (/api/v1/document)

## Models

- [x] User
- [x] Watch
- [x] CalendarEvent
- [x] Location
- [x] NewsPost
- [x] Message
- [x] Permission
- [x] StudentUnion
- [x] Key
- [x] KeyType
- [ ] Document

## Tests for models

- [ ] User
- [ ] Watch
- [x] CalendarEvent
- [x] Location
- [x] NewsPost
- [x] Message
- [x] Permission
- [ ] StudentUnion
- [x] Statistics
- [x] UserStatistics
- [ ] Key
- [ ] KeyType
- [ ] Queue
- [ ] Document

## Tests for utils
- [x] Timestamp filter
- [ ] API route utils
- [ ] iCal utils
- [ ] MessageFactory
- [ ] PermissionUtils
- [ ] Validator

## Improvements

- [x] Use Helmet.js
- [ ] Make controller structure better
- [x] Replace custom validators with Validator.js library
- [x] Create a schema for the API response to standardize API requests between front- and back-ends
- [ ] Add STDU homepage, chairperson & main clubhouse responsible persons to Student Union model
- [ ] Consider combining backend, frontend and shared library repos into a monorepo
- [ ] Modify Rule functionality, so that rules can be grouped and organized (for example, different rules for different topics)
